#include <stdio.h>
/**
 * main-the Fibonacci sequence is generated by adding two terms
 *
 * Return: Always 0
 */
int main(void)
{
	int  t1 = 1, t2 = 2, n_t, sum = 0;

	while (t1 <= 4000000)
	{
		if (t1 % 2 == 0)
			sum += t1;
		n_t = t1 + t2;
		t1 = t2;
		t2 = n_t;
	}
	printf("%d\n", sum);

	return (0);
}

